[2025-01-10T00:15:57.133+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T00:15:57.293+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing.data_transform manual__2025-01-10T00:15:49.426947+00:00 [queued]>
[2025-01-10T00:15:57.305+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing.data_transform manual__2025-01-10T00:15:49.426947+00:00 [queued]>
[2025-01-10T00:15:57.306+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T00:15:57.314+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): data_transform> on 2025-01-10 00:15:49.426947+00:00
[2025-01-10T00:15:57.332+0000] {standard_task_runner.py:72} INFO - Started process 44402 to run task
[2025-01-10T00:15:57.335+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'data_transform', 'manual__2025-01-10T00:15:49.426947+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/job_market_pipeline.py', '--cfg-path', '/tmp/tmp2w33i39c']
[2025-01-10T00:15:57.336+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask data_transform
[2025-01-10T00:15:57.388+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing.data_transform manual__2025-01-10T00:15:49.426947+00:00 [running]> on host bun
[2025-01-10T00:15:59.719+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='data_processing' AIRFLOW_CTX_TASK_ID='data_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T00:15:49.426947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T00:15:49.426947+00:00'
[2025-01-10T00:15:59.756+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-10T00:15:59.874+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-10T00:16:00.070+0000] {logging_mixin.py:190} INFO - Current task name:data_transform state:running start_date:2025-01-10 00:15:57.297900+00:00
[2025-01-10T00:16:00.574+0000] {logging_mixin.py:190} INFO - Dag name:data_processing and current dag run status:running
[2025-01-10T00:16:00.855+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T00:17:01.542+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
[2025-01-10T00:17:01.719+0000] {job.py:229} INFO - Heartbeat recovered after 64.61 seconds
[2025-01-10T00:17:01.869+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-01-10T00:17:06.222+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T00:17:06.580+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 00:15:57.297900+00:00 end:2025-01-10 00:17:06.081994+00:00 duration:68.784094
[2025-01-10T00:17:06.787+0000] {logging_mixin.py:190} INFO - Task:<Task(DockerOperator): data_transform> dag:<DAG: data_processing> dagrun:<DagRun data_processing @ 2025-01-10 00:15:49.426947+00:00: manual__2025-01-10T00:15:49.426947+00:00, state:running, queued_at: 2025-01-10 00:15:49.443450+00:00. externally triggered: True>
[2025-01-10T00:17:08.070+0000] {logging_mixin.py:190} INFO - Failure caused by Failed to establish connection to any given Docker hosts.
[2025-01-10T00:17:08.098+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_processing, task_id=data_transform, run_id=manual__2025-01-10T00:15:49.426947+00:00, execution_date=20250110T001549, start_date=20250110T001557, end_date=20250110T001706
[2025-01-10T00:17:13.275+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T00:17:14.066+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task data_transform (Failed to establish connection to any given Docker hosts.; 44402)
Traceback (most recent call last):
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-01-10T00:17:14.249+0000] {job.py:229} INFO - Heartbeat recovered after 19.19 seconds
[2025-01-10T00:17:14.290+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-10T00:17:14.342+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T00:17:14.364+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
