[2025-01-10T23:45:00.839+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T23:45:00.843+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-10T23:44:58.640099+00:00 [queued]>
[2025-01-10T23:45:00.845+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-10T23:44:58.640099+00:00 [queued]>
[2025-01-10T23:45:00.845+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T23:45:00.850+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): france_travail_data_extraction> on 2025-01-10 23:44:58.640099+00:00
[2025-01-10T23:45:00.855+0000] {standard_task_runner.py:72} INFO - Started process 63570 to run task
[2025-01-10T23:45:00.858+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'france_travail_data_extraction', 'manual__2025-01-10T23:44:58.640099+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/job_market_dag.py', '--cfg-path', '/tmp/tmpui0ar3ja']
[2025-01-10T23:45:00.858+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask france_travail_data_extraction
[2025-01-10T23:45:00.906+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-10T23:44:58.640099+00:00 [running]> on host bun
[2025-01-10T23:45:00.947+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='data_processing' AIRFLOW_CTX_TASK_ID='france_travail_data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T23:44:58.640099+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T23:44:58.640099+00:00'
[2025-01-10T23:45:00.949+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-10T23:45:00.949+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-10T23:45:00.949+0000] {logging_mixin.py:190} INFO - Current task name:france_travail_data_extraction state:running start_date:2025-01-10 23:45:00.843378+00:00
[2025-01-10T23:45:00.949+0000] {logging_mixin.py:190} INFO - Dag name:data_processing and current dag run status:running
[2025-01-10T23:45:00.949+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T23:45:01.014+0000] {docker.py:345} INFO - Starting docker container from image aurel_extract_dock:v3
[2025-01-10T23:45:01.552+0000] {docker.py:69} INFO - python3: can't open file '/app/script/extract.py': [Errno 2] No such file or directory
[2025-01-10T23:45:01.636+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 485, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 350, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 419, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-01-10T23:45:01.639+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T23:45:01.639+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 23:45:00.843378+00:00 end:2025-01-10 23:45:01.639164+00:00 duration:0.795786
[2025-01-10T23:45:01.639+0000] {logging_mixin.py:190} INFO - Task:<Task(DockerOperator): france_travail_data_extraction> dag:<DAG: data_processing> dagrun:<DagRun data_processing @ 2025-01-10 23:44:58.640099+00:00: manual__2025-01-10T23:44:58.640099+00:00, state:running, queued_at: 2025-01-10 23:44:58.681071+00:00. externally triggered: True>
[2025-01-10T23:45:01.639+0000] {logging_mixin.py:190} INFO - Failure caused by Docker container failed: {'StatusCode': 2}
[2025-01-10T23:45:01.639+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_processing, task_id=france_travail_data_extraction, run_id=manual__2025-01-10T23:44:58.640099+00:00, execution_date=20250110T234458, start_date=20250110T234500, end_date=20250110T234501
[2025-01-10T23:45:01.645+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T23:45:01.645+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 59 for task france_travail_data_extraction (Docker container failed: {'StatusCode': 2}; 63570)
Traceback (most recent call last):
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 485, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 350, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 419, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-01-10T23:45:01.682+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-10T23:45:01.692+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T23:45:01.693+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
