[2025-01-11T02:59:24.920+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T02:59:24.925+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing.data_transform manual__2025-01-11T02:59:21.170293+00:00 [queued]>
[2025-01-11T02:59:24.927+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing.data_transform manual__2025-01-11T02:59:21.170293+00:00 [queued]>
[2025-01-11T02:59:24.927+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T02:59:24.937+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): data_transform> on 2025-01-11 02:59:21.170293+00:00
[2025-01-11T02:59:24.945+0000] {standard_task_runner.py:72} INFO - Started process 107946 to run task
[2025-01-11T02:59:24.950+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'data_transform', 'manual__2025-01-11T02:59:21.170293+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/job_market_dag.py', '--cfg-path', '/tmp/tmpkxafta3r']
[2025-01-11T02:59:24.951+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask data_transform
[2025-01-11T02:59:24.997+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing.data_transform manual__2025-01-11T02:59:21.170293+00:00 [running]> on host bun
[2025-01-11T02:59:25.033+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='data_processing' AIRFLOW_CTX_TASK_ID='data_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T02:59:21.170293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T02:59:21.170293+00:00'
[2025-01-11T02:59:25.035+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-11T02:59:25.035+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-11T02:59:25.036+0000] {logging_mixin.py:190} INFO - Current task name:data_transform state:running start_date:2025-01-11 02:59:24.925360+00:00
[2025-01-11T02:59:25.036+0000] {logging_mixin.py:190} INFO - Dag name:data_processing and current dag run status:running
[2025-01-11T02:59:25.036+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T02:59:25.137+0000] {docker.py:345} INFO - Starting docker container from image adzuna_data_transform:latest
[2025-01-11T02:59:27.900+0000] {docker.py:69} INFO - 25/01/11 02:59:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-11T02:59:28.076+0000] {docker.py:69} INFO - Setting default log level to "WARN".
[2025-01-11T02:59:28.077+0000] {docker.py:69} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-01-11T02:59:41.301+0000] {docker.py:69} INFO - Traceback (most recent call last):
[2025-01-11T02:59:41.308+0000] {docker.py:69} INFO -   File "/adzuna/script/adzuna_data_transformation.py", line 101, in <module>
[2025-01-11T02:59:41.309+0000] {docker.py:69} INFO -     .save()
[2025-01-11T02:59:41.309+0000] {docker.py:69} INFO -      ^^^^^^
[2025-01-11T02:59:41.309+0000] {docker.py:69} INFO -   File "/usr/local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 1461, in save
[2025-01-11T02:59:41.309+0000] {docker.py:69} INFO -     self._jwrite.save()
[2025-01-11T02:59:41.310+0000] {docker.py:69} INFO -   File "/usr/local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2025-01-11T02:59:41.310+0000] {docker.py:69} INFO -     return_value = get_return_value(
[2025-01-11T02:59:41.310+0000] {docker.py:69} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-01-11T02:59:41.310+0000] {docker.py:69} INFO -   File "/usr/local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-01-11T02:59:41.311+0000] {docker.py:69} INFO -     return f(*a, **kw)
[2025-01-11T02:59:41.311+0000] {docker.py:69} INFO -            ^^^^^^^^^^^
[2025-01-11T02:59:41.311+0000] {docker.py:69} INFO -   File "/usr/local/lib/python3.12/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-01-11T02:59:41.311+0000] {docker.py:69} INFO -     raise Py4JJavaError(
[2025-01-11T02:59:41.311+0000] {docker.py:69} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o236.save.
[2025-01-11T02:59:41.311+0000] {docker.py:69} INFO - : org.postgresql.util.PSQLException: The connection attempt failed.
[2025-01-11T02:59:41.312+0000] {docker.py:69} INFO - 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:364)
[2025-01-11T02:59:41.312+0000] {docker.py:69} INFO - 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
[2025-01-11T02:59:41.312+0000] {docker.py:69} INFO - 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
[2025-01-11T02:59:41.312+0000] {docker.py:69} INFO - 	at org.postgresql.Driver.makeConnection(Driver.java:446)
[2025-01-11T02:59:41.312+0000] {docker.py:69} INFO - 	at org.postgresql.Driver.connect(Driver.java:298)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider.getConnection(BasicConnectionProvider.scala:49)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.connection.ConnectionProviderBase.create(ConnectionProvider.scala:102)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.jdbc.JdbcDialect.$anonfun$createConnectionFactory$1(JdbcDialects.scala:161)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.jdbc.JdbcDialect.$anonfun$createConnectionFactory$1$adapted(JdbcDialects.scala:157)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:50)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[2025-01-11T02:59:41.313+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-01-11T02:59:41.314+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-01-11T02:59:41.315+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-01-11T02:59:41.316+0000] {docker.py:69} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - Caused by: java.net.UnknownHostException: postgres_db
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
[2025-01-11T02:59:41.317+0000] {docker.py:69} INFO - 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[2025-01-11T02:59:41.318+0000] {docker.py:69} INFO - 	at java.base/java.net.Socket.connect(Socket.java:633)
[2025-01-11T02:59:41.318+0000] {docker.py:69} INFO - 	at org.postgresql.core.PGStream.createSocket(PGStream.java:260)
[2025-01-11T02:59:41.318+0000] {docker.py:69} INFO - 	at org.postgresql.core.PGStream.<init>(PGStream.java:121)
[2025-01-11T02:59:41.318+0000] {docker.py:69} INFO - 	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:140)
[2025-01-11T02:59:41.318+0000] {docker.py:69} INFO - 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:268)
[2025-01-11T02:59:41.318+0000] {docker.py:69} INFO - 	... 50 more
[2025-01-11T02:59:41.592+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 485, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 350, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 419, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-01-11T02:59:41.598+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T02:59:41.598+0000] {logging_mixin.py:190} INFO - Task start:2025-01-11 02:59:24.925360+00:00 end:2025-01-11 02:59:41.596710+00:00 duration:16.67135
[2025-01-11T02:59:41.598+0000] {logging_mixin.py:190} INFO - Task:<Task(DockerOperator): data_transform> dag:<DAG: data_processing> dagrun:<DagRun data_processing @ 2025-01-11 02:59:21.170293+00:00: manual__2025-01-11T02:59:21.170293+00:00, state:running, queued_at: 2025-01-11 02:59:21.204682+00:00. externally triggered: True>
[2025-01-11T02:59:41.598+0000] {logging_mixin.py:190} INFO - Failure caused by Docker container failed: {'StatusCode': 1}
[2025-01-11T02:59:41.599+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_processing, task_id=data_transform, run_id=manual__2025-01-11T02:59:21.170293+00:00, execution_date=20250111T025921, start_date=20250111T025924, end_date=20250111T025941
[2025-01-11T02:59:41.610+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T02:59:41.610+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task data_transform (Docker container failed: {'StatusCode': 1}; 107946)
Traceback (most recent call last):
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 485, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 350, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adm1n/job_market/.venv/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 419, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-01-11T02:59:41.640+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-11T02:59:41.653+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T02:59:41.654+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
